### ISSUE TITLE
Please change the license

### ISSUE THREAD

**Issue by Secret-chest** [Explosion-Scratch/OnDrop#31]
### Contact Details

On this issue, just mention @Secret-chest

### What's your idea?

Change the license to AGPL.

## Why?

It might look like it, but the CC BY-NC-SA is not a free license. Also, CC licenses are not suitable for software because they don't especially address the source code.

The AGPL will also prevent this from being used on servers without sharing the source code.

**Comment by Explosion-Scratch** [comment]
I would like to require people to share (at least a link) to the source code if they use this code.

**Comment by Explosion-Scratch** [comment]
Can you outline what else AGPL allows and doesn't allow?

**Comment by Secret-chest** [comment]
The AGPL requires that anyone who uses the program must provide source code too and they can't change the license. They must also credit you.

**Comment by Explosion-Scratch** [comment]
Cool! Will change! Thanks for bringing this up!

**Comment by Secret-chest** [comment]
> Cool! Will change! Thanks for bringing this up!

You're welcome. ¯\_(ツ)_/¯
