### ISSUE TITLE
[Bug]: Mobile devices cannot send/recieve files to/from desktop devices

### ISSUE THREAD

**Issue by JoshAtticus** [Explosion-Scratch/OnDrop#35]
### Contact Details

JoshAtticus on Meower & Revolt (I don't have Discord :D)

### What happened?

When sending files to or from a mobile device using a desktop device (and vice versa), the file does not send. It says encrypting, then does nothing else.

Devices tested

- iPhone 6s iOS 15.7.1 (Mobile Safari) --> Ubuntu 22.10 (Firefox & Vivaldi)
- iPhone 6s iOS 15.7.1 (Mobile Safari) --> Windows 11 Home (Microsoft Edge & Vivaldi)
- iPhone 8 iOS 16.3 Public Beta (Mobile Safari) --> Ubuntu 22.10 (Firefox & Vivaldi)
- iPhone 8 iOS 16.3 Public Beta (Mobile Safari) --> Windows 11 Home (Microsoft Edge & Vivaldi)
- Samsung Galaxy Tab A7 Android 12 (Google Chrome & Samsung Internet) --> Ubuntu 22.10 (Firefox & Vivaldi)
- Samsung Galaxy Tab A7 Android 12 (Google Chrome & Samsung Internet) --> Windows 11 Home (Microsoft Edge & Vivaldi)
- Samsung Galaxy S4 Lineage OS 18.1 (Chromium & Vivaldi) --> Ubuntu 22.10 (Firefox & Vivaldi)
- Samsung Galaxy S4 Lineage OS 18.1 (Chromium & Vivaldi) --> Windows 11 Home (Microsoft Edge & Vivaldi)

### Did you modify OnDrop in any way?

- [ ] Check the box if you were

### What browsers are you seeing the problem on? (Select multiple if needed)

Firefox, Chrome, Safari

### Relevant log output

```shell
No errors appeared in popups or browser consoles
```

### Read the README

- [X] Check the box if you read it

**Comment by Explosion-Scratch** [comment]
Huh, will check on this, sorry for the late reply

**Comment by Explosion-Scratch** [comment]
Were you on the same wifi network with both of these? Do the devices both show up?

**Comment by JoshAtticus** [comment]
> Were you on the same wifi network with both of these? Do the devices both show up?

Yes to both

**Comment by Explosion-Scratch** [comment]
Closing as I made some fixes and it's still working for me
